In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
base = pd.read_csv('/content/credit_data.csv')

In [ ]:
base.describe()

i#clientid        income          age          loan    c#default
count  2000.000000   2000.000000  1997.000000   2000.000000  2000.000000
mean   1000.500000  45331.600018    40.807559   4444.369695     0.141500
std     577.494589  14326.327119    13.624469   3045.410024     0.348624
min       1.000000  20014.489470   -52.423280      1.377630     0.000000
25%     500.750000  32796.459717    28.990415   1939.708847     0.000000
50%    1000.500000  45789.117313    41.317159   3974.719419     0.000000
75%    1500.250000  57791.281668    52.587040   6432.410625     0.000000
max    2000.000000  69995.685578    63.971796  13766.051239     1.000000

Localiza na base as idades menores que 0

In [ ]:
base.loc[base['age'] < 0]

Empty DataFrame
Columns: [i#clientid, income, age, loan, c#default]
Index: []

Exemplo de Exclusão, porem não recomendavel

In [ ]:
base.drop(base[base.age < 0].index, inplace=True)

In [ ]:
base.mean()

i#clientid     1000.500000
income        45331.600018
age              40.807559
loan           4444.369695
c#default         0.141500
dtype: float64

Não é recomendavel apagar os registro é bom colocar as medias de idades 

In [ ]:
base['age'][base.age > 0].mean()

40.92770044906149

In [ ]:
base.loc[base.age < 0, 'age'] = base['age'][base.age > 0].mean()

In [ ]:
base.loc[pd.isnull(base['age'])]

i#clientid        income  age         loan  c#default
28          29  59417.805406  NaN  2082.625938          0
30          31  48528.852796  NaN  6155.784670          0
31          32  23526.302555  NaN  2862.010139          0

In [ ]:
previsores = base.iloc[:, 1:4]

In [ ]:
previsores.describe()

income          age          loan
count   2000.000000  1997.000000   2000.000000
mean   45331.600018    40.927700   4444.369695
std    14326.327119    13.261825   3045.410024
min    20014.489470    18.055189      1.377630
25%    32796.459717    29.072097   1939.708847
50%    45789.117313    41.317159   3974.719419
75%    57791.281668    52.587040   6432.410625
max    69995.685578    63.971796  13766.051239

In [ ]:
classe = base.iloc[:, 4].values

In [ ]:
classe

array([0, 0, 0, ..., 1, 0, 0])

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(previsores.iloc[:, 0:3])
previsores.iloc[:,0:3] = imputer.transform(previsores.iloc[:,0:3])

In [ ]:
previsores.describe()

income          age          loan
count   2000.000000  2000.000000   2000.000000
mean   45331.600018    40.927700   4444.369695
std    14326.327119    13.251870   3045.410024
min    20014.489470    18.055189      1.377630
25%    32796.459717    29.102161   1939.708847
50%    45789.117313    41.300710   3974.719419
75%    57791.281668    52.582340   6432.410625
max    69995.685578    63.971796  13766.051239

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)
                 

In [ ]:
previsores

array([[ 1.45393393,  1.36538093,  1.20281942],
       [-0.76217555,  0.5426602 ,  0.69642695],
       [ 0.83682073,  1.67417189,  1.17471147],
       ...,
       [-0.07122592, -0.97448519,  0.35420081],
       [-0.11000289,  1.73936739, -0.92675625],
       [ 1.682986  ,  1.14917639,  0.96381038]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(previsores, classe, test_size = 0.2, random_state = 5)

In [ ]:
X_train.shape

(1600, 3)

In [ ]:
classifier = tf.keras.models.Sequential()
classifier.add(tf.keras.layers.Dense(units=10, activation='relu', input_shape=(3, )))
classifier.add(tf.keras.layers.Dense(units=10, activation='relu'))
classifier.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [ ]:
classifier.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_24 (Dense)             (None, 10)                40        
_________________________________________________________________
dense_25 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_26 (Dense)             (None, 1)                 11        
Total params: 161
Trainable params: 161
Non-trainable params: 0
_________________________________________________________________


In [ ]:
classifier.compile(optimizer='Adam', loss='binary_crossentropy', metrics = ['accuracy'])

In [ ]:
epochs_hist = classifier.fit(X_train, y_train, epochs=400)

Epoch 1/400
50/50 [==============================] - 0s 1ms/step - loss: 0.0025 - accuracy: 0.9994
Epoch 2/400
50/50 [==============================] - 0s 1ms/step - loss: 0.0029 - accuracy: 0.9987
Epoch 3/400
50/50 [==============================] - 0s 1ms/step - loss: 0.0031 - accuracy: 0.9994
Epoch 4/400
50/50 [==============================] - 0s 1ms/step - loss: 0.0027 - accuracy: 1.0000
Epoch 5/400
50/50 [==============================] - 0s 1ms/step - loss: 0.0030 - accuracy: 0.9987
Epoch 6/400
50/50 [==============================] - 0s 1ms/step - loss: 0.0026 - accuracy: 1.0000
Epoch 7/400
50/50 [==============================] - 0s 1ms/step - loss: 0.0028 - accuracy: 0.9994
Epoch 8/400
50/50 [==============================] - 0s 1ms/step - loss: 0.0024 - accuracy: 1.0000
Epoch 9/400
50/50 [==============================] - 0s 1ms/step - loss: 0.0026 - accuracy: 0.9994
Epoch 10/400
50/50 [==============================] - 0s 1ms/step - loss: 0.0023 - accuracy: 1.0000
Epoch 11/

In [ ]:
base[base['c#default'] == 0]

i#clientid        income        age         loan  c#default
0              1  66155.925095  59.017015  8106.532131          0
1              2  34415.153966  48.117153  6564.745018          0
2              3  57317.170063  63.108049  8020.953296          0
3              4  42709.534201  45.751972  6103.642260          0
5              6  24904.064140  57.471607    15.498598          0
...          ...           ...        ...          ...        ...
1994        1995  24254.700791  37.751622  2225.284643          0
1995        1996  59221.044874  48.518179  1926.729397          0
1996        1997  69516.127573  23.162104  3503.176156          0
1998        1999  43756.056605  63.971796  1622.722598          0
1999        2000  69436.579552  56.152617  7378.833599          0

[1717 rows x 5 columns]

In [ ]:
verdadeiros

array([False, False, False, ...,  True, False, False])

In [ ]:
predicao = classifier.predict(scaler.transform([[24254.700791,35,0]]))
predicao > 0.5

array([[False]])